### ISSUE TITLE
Waydroid won't start of Debian 11 under Weston

### ISSUE THREAD

**Issue by SSUPII** [Aman9das/Waydroid_Setup_Guide#7]
```[gbinder] WARNING: Unknown gbinder config 'aidl3' for /dev/anbox-binder in group [ServiceManager]
[gbinder] WARNING: Unknown gbinder config 'aidl3' for /dev/anbox-vndbinder in group [ServiceManager]
[gbinder] WARNING: Unknown gbinder config 'aidl3' for /dev/anbox-binder in group [Protocol]
[gbinder] WARNING: Unknown gbinder config 'aidl3' for /dev/anbox-vndbinder in group [Protocol]
[gbinder] Service manager /dev/anbox-binder has appeared
[11:50:14] Failed to add service waydroidhardware: -1
[11:50:15] session manager stopped, stopping container and waiting...
[11:50:15] WayDroid container is STOPPED
```
I think I followed the instructions for Waydroid on X11 well, unless I am missing something here.

**Comment by Aman9das** [comment]
Are you certain you are using android 11 image?

try running ```waydroid init -f``` and try again. check /usr/share/waydroid-extra/images has 2 files

**Comment by SSUPII** [comment]
Here is the content of `/usr/share/waydroid-extra/images`
```
sergio@debian:~$ ls -sa /usr/share/waydroid-extra/images
totale 4975564
      4 .        4 ..  3464340 system.img  1511216 vendor.img
```
Running `waydroid init -f` and then trying again makes no change.
      
Here is the full `waydroid log`, and it appears some mounts are failing
```
(017086) [14:20:41] XDG Session is not "wayland"
(017086) [14:20:41] Save session config: /var/lib/waydroid/session.cfg
(017086) [14:20:41] UserMonitor service is not even started
(017086) [14:20:41] Clipboard service is not even started
(017081) [14:20:41] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
waydroid-net is already running
(017081) [14:20:41] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(017081) [14:20:41] % umount /var/lib/waydroid/rootfs/vendor
(017081) [14:20:41] % umount /var/lib/waydroid/rootfs
(017081) [14:20:41] % mount /usr/share/waydroid-extra/images/system.img /var/lib/waydroid/rootfs
(017081) [14:20:41] % mount -o remount,ro /usr/share/waydroid-extra/images/system.img /var/lib/waydroid/rootfs
(017081) [14:20:41] % mount /usr/share/waydroid-extra/images/vendor.img /var/lib/waydroid/rootfs/vendor
(016908) [14:20:41] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
waydroid-net is already running
(016908) [14:20:41] % umount /var/lib/waydroid/rootfs
(016908) [14:20:41] % mount /usr/share/waydroid-extra/images/system.img /var/lib/waydroid/rootfs
mount: /var/lib/waydroid/rootfs/vendor: mount point does not exist.
(017081) [14:20:41] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(017081) [14:20:41] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(017081) [14:20:41] ERROR: Command failed: % mount /usr/share/waydroid-extra/images/vendor.img /var/lib/waydroid/rootfs/vendor
(017081) [14:20:41] See also: <https://github.com/waydroid>
(017081) [14:20:41] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 69, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 132, in start
    helpers.images.mount_rootfs(args, cfg["waydroid"]["images_path"])
  File "/usr/lib/waydroid/tools/helpers/images.py", line 100, in mount_rootfs
    helpers.mount.mount(args, images_dir + "/vendor.img",
  File "/usr/lib/waydroid/tools/helpers/mount.py", line 131, in mount
    tools.helpers.run.user(args, ["mount", source, destination])
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % mount /usr/share/waydroid-extra/images/vendor.img /var/lib/waydroid/rootfs/vendor

(016908) [14:20:41] % mount -o remount,ro /usr/share/waydroid-extra/images/system.img /var/lib/waydroid/rootfs
(016908) [14:20:41] % mount /usr/share/waydroid-extra/images/vendor.img /var/lib/waydroid/rootfs/vendor
(016908) [14:20:41] % mount -o remount,ro /usr/share/waydroid-extra/images/vendor.img /var/lib/waydroid/rootfs/vendor
(016908) [14:20:41] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(016908) [14:20:41] % umount -l /sys/fs/cgroup/schedtune
umount: /sys/fs/cgroup/schedtune: no mount point specified.
(016908) [14:20:41] % chmod 777 -R /dev/ashmem
(016908) [14:20:41] % chmod 777 -R /dev/dri
(016908) [14:20:41] % chmod 777 -R /dev/fb0
(016908) [14:20:41] % chmod 777 -R /dev/video1
(016908) [14:20:41] % chmod 777 -R /dev/video0
(016908) [14:20:41] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(016908) [14:20:41] New background process: pid=17142, output=background
lxc-start: waydroid: cgroups/cgroup2_devices.c: bpf_program_load_kernel: 348 Operation not permitted - Failed to load bpf program: (null)
(016908) [14:20:42] Save session config: /var/lib/waydroid/session.cfg
(016908) [14:20:42] Failed to add service waydroidhardware: -2147483647
(017086) [14:20:42] Failed to start Clipboard manager service, check logs
(017086) [14:20:42] Failed to add service waydroidusermonitor: -2147483647
lxc-start: waydroid: conf.c: run_buffer: 314 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 958 Failed to run lxc.hook.post-stop for container "waydroid"
(017210) [14:21:48] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(017210) [14:21:48] *** output passed to waydroid stdout, not to this log ***
```

**Comment by Aman9das** [comment]
> You may need to umount -a and waydroid session stop for Libhoudini to install.

**Comment by SSUPII** [comment]
> > You may need to umount -a and waydroid session stop for Libhoudini to install.

No change. I also tried running it into a native Wayland session, but it still fails on `lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init`
